### PR TITLE
Fix Issue #9

### LINKED ISSUE #9: Using multiple JSON serialisers is confusing
[vnfm-sdk-rest](https://github.com/openbaton/openbaton-libs/tree/master/vnfm-sdk-rest) uses Jackson, while the rest of the project uses Gson to serialise/deserialise JSON.

This can lead to an inconsistent and confusing serialisation behaviour, like in [VirtualNetworkFunctionRecord](https://github.com/openbaton/openbaton-libs/blob/master/catalogue/src/main/java/org/openbaton/catalogue/mano/descriptor/VirtualNetworkFunctionDescriptor.java#L96), where the `endpoint` field is marked `@JsonIgnore` using a Jackson tag, but it's still considered (correctly) when using Gson.

I would consider dropping Jackson to reduce these ambiguities and make the way the project handles JSON more consistent.

### PR DESCRIPTION
**Pull request by marcellom**
Remove dependencies with Jackson.
resolves #9

### CODE REVIEW

**Comment by gc4rella** [comment]
@mpauls @lorenzotomasini I have some doubts about passing the endpoint in the VNFD, could you please double check?

**Comment by marcellom** [comment]
Actually the endpoint is already passed, the @JsonIgnore does not work with Gson. I realized it after the commit b2a6ccbe4d0ddf64e94c8b09595b2362eb0bbf22 because intergration tests were failing.

**Comment by lorenzotomasini** [comment]
the endpoint corresponds to the Vnfm configuration property. If the Vnfm receives that VNFD, it means that this vnfd has this specific endpoint.

in which case should we not send the endpoint?

**Comment by lorenzotomasini** [comment]
done in nfvo

**Pull request closed without merging**
